"""Loop lifecycle management - mirrors ralph.py's run_loop() for web.

Execution pattern:
1. Create PROMPT_{mode}.md in feature_dir from template (if not exists)
2. Generate loop.ps1 (Windows) or loop.sh (Mac) in feature_dir with config baked in
3. Run the script with cwd=project_path (project root) so Claude starts there
4. Script uses absolute paths to feature_dir for prompt/progress files
5. Clean up generated files when done
"""
import asyncio
import json
import os
import platform
import signal
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional

from server import config
from server.models.loop_state import LoopInstance
from server.services.output_parser import OutputParser
from server.services.provider_service import Provider, get_provider_by_name, ClaudeProvider


# Identical to ralph.py's LOOP_SCRIPT_TEMPLATE (lines 24-119)
# The server uses the same template so the generated script behaves identically
LOOP_PS1_TEMPLATE = '''# Feature Loop - Auto-generated by server
# This file will be deleted after the loop completes

param(
    [ValidateSet("plan", "build")]
    [string]$Mode = "{mode}",
    [int]$MaxIterations = {max_iterations},
    [string]$Model = "{model}"
)

# Absolute paths baked in by server - no relative resolution needed
$FeatureDir = "{feature_dir}"
$ProjectRoot = "{project_root}"

# Prevent child MCP servers from opening the browser
$env:RALPH_SERVER_AUTO_OPEN = "false"

$PromptFile = Join-Path $FeatureDir "PROMPT_$Mode.md"
$ProgressFile = Join-Path $FeatureDir "progress.txt"
$TaskFile = Join-Path $FeatureDir "task.md"

$CurrentBranch = git branch --show-current

Write-Output "Feature:  {feature_name}"
Write-Output "Provider: {provider_name}"
Write-Output "Mode:     $Mode"
Write-Output "Model:    $Model"
Write-Output "Branch:   $CurrentBranch"
Write-Output "Project:  $ProjectRoot"
Write-Output "Prompt:   $PromptFile"
if ($MaxIterations -gt 0) {{
    Write-Output "Max:     $MaxIterations iterations"
}} else {{
    Write-Output "Max:     unlimited"
}}

if (-not (Test-Path $PromptFile)) {{
    Write-Output "Error: $PromptFile not found"
    exit 1
}}

$Iteration = 0

while ($true) {{
    if ($MaxIterations -gt 0 -and $Iteration -ge $MaxIterations) {{
        Write-Output "Reached max iterations: $MaxIterations"
        break
    }}

    $Iteration++
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

    Write-Output ""
    Write-Output "======================== ITERATION $Iteration ========================"
    Write-Output "Started: $Timestamp"
    Write-Output ""

    $PromptContent = Get-Content $PromptFile -Raw
    $TaskContent = Get-Content $TaskFile -Raw -ErrorAction SilentlyContinue
    $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
    if ($TaskContent) {{
        $PromptContent = "$PromptContent`n`n## Task`n$TaskContent"
    }}
    if ($ProgressContent) {{
        $PromptContent = "$PromptContent`n`n## Current Progress`n$ProgressContent"
    }}
    {invocation_block}
    $AgentExitCode = $LASTEXITCODE
    if ($AgentExitCode -ne 0) {{
        Write-Output "Agent invocation failed with exit code $AgentExitCode"
        exit $AgentExitCode
    }}

    git push origin $CurrentBranch 2>$null
    if ($LASTEXITCODE -ne 0) {{
        Write-Output "Failed to push. Creating remote branch..."
        git push -u origin $CurrentBranch 2>$null
    }}
    $LASTEXITCODE = 0

    Write-Output ""
    Write-Output "[$(Get-Date -Format 'yyyy-MM-dd HH:mm')] ITERATION $Iteration complete"

    if ($Mode -eq "build") {{
        $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
        if ($ProgressContent -match "ALL PHASES COMPLETE") {{
            Write-Output "All phases complete! Stopping loop."
            break
        }}
    }}
}}

Write-Output ""
Write-Output "Loop finished after $Iteration iteration(s)"
Write-Output "Check: $ProgressFile"
exit 0
'''

# Bash equivalent of the above for Mac/Linux
LOOP_SH_TEMPLATE = '''#!/bin/bash
# Feature Loop - Auto-generated by server
# This file will be deleted after the loop completes

MODE="{mode}"
MAX_ITERATIONS={max_iterations}
MODEL="{model}"

# Absolute paths baked in by server - no relative resolution needed
FEATURE_DIR="{feature_dir}"
PROJECT_ROOT="{project_root}"

# Prevent child MCP servers from opening the browser
export RALPH_SERVER_AUTO_OPEN="false"

PROMPT_FILE="$FEATURE_DIR/PROMPT_$MODE.md"
PROGRESS_FILE="$FEATURE_DIR/progress.txt"
TASK_FILE="$FEATURE_DIR/task.md"

CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

echo "Feature:  {feature_name}"
echo "Provider: {provider_name}"
echo "Mode:     $MODE"
echo "Model:    $MODEL"
echo "Branch:   $CURRENT_BRANCH"
echo "Project:  $PROJECT_ROOT"
echo "Prompt:   $PROMPT_FILE"
if [ "$MAX_ITERATIONS" -gt 0 ] 2>/dev/null; then
    echo "Max:     $MAX_ITERATIONS iterations"
else
    echo "Max:     unlimited"
fi

if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: $PROMPT_FILE not found"
    exit 1
fi

ITERATION=0

while true; do
    if [ "$MAX_ITERATIONS" -gt 0 ] 2>/dev/null && [ "$ITERATION" -ge "$MAX_ITERATIONS" ]; then
        echo "Reached max iterations: $MAX_ITERATIONS"
        break
    fi

    ITERATION=$((ITERATION + 1))
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

    echo ""
    echo "======================== ITERATION $ITERATION ========================"
    echo "Started: $TIMESTAMP"
    echo ""

    PROMPT_CONTENT=$(cat "$PROMPT_FILE")
    if [ -f "$TASK_FILE" ]; then
        TASK_CONTENT=$(cat "$TASK_FILE")
        if [ -n "$TASK_CONTENT" ]; then
            PROMPT_CONTENT="$PROMPT_CONTENT

## Task
$TASK_CONTENT"
        fi
    fi
    if [ -f "$PROGRESS_FILE" ]; then
        PROGRESS_CONTENT=$(cat "$PROGRESS_FILE")
        if [ -n "$PROGRESS_CONTENT" ]; then
            PROMPT_CONTENT="$PROMPT_CONTENT

## Current Progress
$PROGRESS_CONTENT"
        fi
    fi

    {invocation_block}
    AGENT_EXIT=$?
    if [ "$AGENT_EXIT" -ne 0 ]; then
        echo "Agent invocation failed with exit code $AGENT_EXIT"
        exit "$AGENT_EXIT"
    fi

    git push origin "$CURRENT_BRANCH" 2>/dev/null || {{
        echo "Creating remote branch..."
        git push -u origin "$CURRENT_BRANCH" 2>/dev/null || true
    }}

    echo ""
    echo "[$(date '+%Y-%m-%d %H:%M')] ITERATION $ITERATION complete"

    if [ "$MODE" = "build" ]; then
        if grep -q "ALL PHASES COMPLETE" "$PROGRESS_FILE" 2>/dev/null; then
            echo "All phases complete! Stopping loop."
            break
        fi
    fi
done

echo ""
echo "Loop finished after $ITERATION iteration(s)"
echo "Check: $PROGRESS_FILE"
exit 0
'''


class LoopService:
    def __init__(self):
        self._loops: dict[str, LoopInstance] = {}
        self._processes: dict[str, subprocess.Popen] = {}
        self._subscribers: dict[str, list[asyncio.Queue]] = {}
        self._tasks: dict[str, asyncio.Task] = {}
        self._created_files: dict[str, list[Path]] = {}  # project_id -> files to clean up

    def get_state(self, project_id: str) -> Optional[LoopInstance]:
        return self._loops.get(project_id)

    def get_all_states(self) -> dict[str, LoopInstance]:
        return self._loops

    @staticmethod
    def _record_action(instance: LoopInstance, message: str, action_type: str = "event") -> None:
        instance.recent_actions.append(
            {
                "time": datetime.now().isoformat(timespec="seconds"),
                "type": action_type,
                "message": message,
            }
        )

    async def start_loop(
        self,
        project_id: str,
        project_path: str,
        feature_name: str,
        mode: str,
        model: str,
        max_iterations: int = 0,
        provider: Provider | None = None,
    ) -> LoopInstance:
        """Start a ralph loop - mirrors ralph.py's run_loop() exactly."""
        # Default to Claude if no provider specified (backward compat)
        if provider is None:
            provider = ClaudeProvider()

        # Check if already running
        existing = self._loops.get(project_id)
        if existing and existing.status in ("running", "starting"):
            raise ValueError("A loop is already running for this project")

        feature_dir = Path(project_path) / ".vista" / "features" / feature_name
        if not feature_dir.exists():
            raise ValueError(f"Feature directory not found: {feature_dir}")

        created_files = []

        # --- Step 1: Create prompt file (mirrors ralph.py lines 191-200) ---
        prompt_file = feature_dir / f"PROMPT_{mode}.md"
        if not prompt_file.exists():
            prompt_content = self._get_prompt_content(mode, feature_name, feature_dir, project_path)
            if not prompt_content:
                raise ValueError(f"No prompt template found for mode: {mode}")
            prompt_file.write_text(prompt_content, encoding="utf-8")
            created_files.append(prompt_file)

        # --- Step 2: Create loop script (mirrors ralph.py lines 203-214) ---
        # Normalize paths for the target platform
        feature_dir_str = str(feature_dir).replace("\\", "/")
        project_root_str = str(Path(project_path).resolve()).replace("\\", "/")

        if platform.system() == "Windows":
            loop_script = feature_dir / "loop.ps1"
            script_content = LOOP_PS1_TEMPLATE.format(
                mode=mode,
                max_iterations=max_iterations,
                model=model,
                feature_name=feature_name,
                feature_dir=str(feature_dir),
                project_root=str(Path(project_path).resolve()),
                provider_name=provider.display_name,
                invocation_block=provider.get_invocation("ps1"),
            )
            loop_script.write_text(script_content, encoding="utf-8")
            created_files.append(loop_script)
            cmd = ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(loop_script)]
        else:
            loop_script = feature_dir / "loop.sh"
            script_content = LOOP_SH_TEMPLATE.format(
                mode=mode,
                max_iterations=max_iterations,
                model=model,
                feature_name=feature_name,
                feature_dir=feature_dir_str,
                project_root=project_root_str,
                provider_name=provider.display_name,
                invocation_block=provider.get_invocation("sh"),
            )
            loop_script.write_text(script_content, encoding="utf-8")
            os.chmod(str(loop_script), 0o755)
            created_files.append(loop_script)
            cmd = ["bash", str(loop_script)]

        self._created_files[project_id] = created_files

        # Create LoopInstance
        instance = LoopInstance(
            project_id=project_id,
            feature_name=feature_name,
            mode=mode,
            model=model,
            provider=provider.name,
            provider_display_name=provider.display_name,
            status="starting",
            max_iterations=max_iterations,
            start_time=datetime.now().isoformat(),
        )
        self._loops[project_id] = instance
        self._record_action(instance, f"Loop started ({mode})", "lifecycle")

        # --- Step 3: Run the script from the project root ---
        proc = subprocess.Popen(
            cmd,
            stdin=subprocess.DEVNULL,  # Prevent child from reading MCP stdin
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=str(Path(project_path).resolve()),  # Run from project root
            text=True,
            encoding="utf-8",
            errors="replace",  # Replace undecodable bytes instead of crashing
            bufsize=1,
        )

        instance.pid = proc.pid
        instance.status = "running"
        self._processes[project_id] = proc

        # Start async output reader
        self._tasks[project_id] = asyncio.create_task(
            self._read_output(project_id, proc)
        )

        await self._broadcast(project_id, {
            "event": "loop_started",
            "data": instance.to_dict()
        })

        return instance

    @staticmethod
    def _get_prompt_content(mode: str, feature_name: str, feature_dir: Path, project_path: str) -> Optional[str]:
        """Get prompt content from template - mirrors ralph.py's get_prompt_content() lines 160-175."""
        template_file = config.TEMPLATES_DIR / f"PROMPT_{mode}.md"
        if not template_file.exists():
            return None

        content = template_file.read_text(encoding="utf-8")

        # Same variable substitution as ralph.py lines 171-173
        content = content.replace("{{FEATURE_NAME}}", feature_name)
        content = content.replace("{{FEATURE_DIR}}", str(feature_dir).replace("\\", "/"))
        content = content.replace("{{PROJECT_NAME}}", Path(project_path).name)

        return content

    def _cleanup_files(self, project_id: str):
        """Clean up generated files - mirrors ralph.py's finally block lines 233-244."""
        created = self._created_files.pop(project_id, [])
        for f in created:
            try:
                if f.exists():
                    f.unlink()
            except Exception:
                pass

    async def _read_output(self, project_id: str, proc: subprocess.Popen):
        """Read subprocess stdout line-by-line, parse events, update state."""
        instance = self._loops[project_id]
        parser = OutputParser()

        try:
            loop = asyncio.get_running_loop()
            while True:
                line = await loop.run_in_executor(None, proc.stdout.readline)
                if not line:
                    break

                line = line.rstrip("\n\r")
                instance.output_lines.append(line)

                events = parser.parse_line(line)
                for event in events:
                    if event.event_type == "iteration_start":
                        instance.iteration = event.data["iteration"]
                        self._record_action(
                            instance,
                            f"Iteration {event.data['iteration']} started",
                            "iteration",
                        )
                    elif event.event_type == "iteration_complete":
                        self._record_action(
                            instance,
                            f"Iteration {event.data['iteration']} complete",
                            "iteration",
                        )
                    elif event.event_type == "ralph_control":
                        instance.last_ralph_control = event.data
                        status = event.data.get("status") or "updated"
                        files = event.data.get("files_changed")
                        summary = f"RALPH_CONTROL {status}"
                        if files:
                            summary += f" ({files} files changed)"
                        self._record_action(instance, summary, "control")
                    elif event.event_type == "loop_finished":
                        instance.status = "completed"
                        self._record_action(instance, "Loop finished", "lifecycle")
                    elif event.event_type == "all_phases_complete":
                        instance.status = "completed"
                        self._record_action(instance, "All phases complete", "lifecycle")

                stripped = line.strip()
                if stripped.startswith("> Tool:"):
                    self._record_action(instance, stripped, "tool")

                await self._broadcast(project_id, {
                    "event": "output",
                    "data": {"line": line, "parsed": [{"type": e.event_type, **e.data} for e in events]}
                })

            await loop.run_in_executor(None, proc.wait)

            if instance.status == "running":
                instance.status = "completed" if proc.returncode == 0 else "failed"
                if proc.returncode != 0:
                    # Capture last output lines for context
                    last_lines = list(instance.output_lines)[-10:]
                    context = "\n".join(last_lines) if last_lines else "(no output)"
                    instance.error = f"Process exited with code {proc.returncode}\nLast output:\n{context}"
                    self._record_action(instance, f"Process failed with exit code {proc.returncode}", "lifecycle")
                else:
                    self._record_action(instance, "Process exited successfully", "lifecycle")

        except asyncio.CancelledError:
            pass
        except Exception as e:
            instance.status = "failed"
            instance.error = f"{type(e).__name__}: {e}"
            self._record_action(instance, f"Loop failed: {type(e).__name__}", "lifecycle")
        finally:
            instance.end_time = datetime.now().isoformat()
            # Step 4: Clean up generated files (mirrors ralph.py's finally block)
            self._cleanup_files(project_id)
            await self._broadcast(project_id, {
                "event": "loop_ended",
                "data": instance.to_dict()
            })
            self._processes.pop(project_id, None)
            self._tasks.pop(project_id, None)

    async def stop_loop(self, project_id: str) -> Optional[LoopInstance]:
        """Stop a running loop by terminating the subprocess."""
        instance = self._loops.get(project_id)
        if not instance or instance.status not in ("running", "starting"):
            return instance

        proc = self._processes.get(project_id)
        if proc:
            try:
                if platform.system() == "Windows":
                    proc.terminate()
                else:
                    proc.send_signal(signal.SIGTERM)
                # Give it 5 seconds to die
                try:
                    loop = asyncio.get_running_loop()
                    await asyncio.wait_for(
                        loop.run_in_executor(None, proc.wait),
                        timeout=5.0
                    )
                except asyncio.TimeoutError:
                    proc.kill()
            except ProcessLookupError:
                pass  # Already dead

        # Cancel the reader task and wait for its finally block to complete
        task = self._tasks.get(project_id)
        if task and not task.done():
            task.cancel()
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass

        instance.status = "stopped"
        instance.end_time = datetime.now().isoformat()
        self._record_action(instance, "Loop stopped by user", "lifecycle")

        await self._broadcast(project_id, {
            "event": "loop_stopped",
            "data": instance.to_dict()
        })

        return instance

    async def stop_all(self):
        """Stop all running loops (called on server shutdown)."""
        for project_id in list(self._loops.keys()):
            await self.stop_loop(project_id)

    # --- SSE Subscriber Management ---

    def subscribe(self, project_id: str) -> asyncio.Queue:
        """Register an SSE subscriber for a project's loop output."""
        if project_id not in self._subscribers:
            self._subscribers[project_id] = []
        queue = asyncio.Queue(maxsize=1000)
        self._subscribers[project_id].append(queue)
        return queue

    def unsubscribe(self, project_id: str, queue: asyncio.Queue):
        """Remove an SSE subscriber."""
        if project_id in self._subscribers:
            self._subscribers[project_id] = [
                q for q in self._subscribers[project_id] if q is not queue
            ]

    async def _broadcast(self, project_id: str, message: dict):
        """Send a message to all SSE subscribers for a project."""
        if project_id not in self._subscribers:
            return
        dead_queues = []
        for queue in self._subscribers[project_id]:
            try:
                queue.put_nowait(message)
            except asyncio.QueueFull:
                dead_queues.append(queue)
        for q in dead_queues:
            self._subscribers[project_id].remove(q)


# Singleton instance
loop_service = LoopService()
