# Feature Loop - Auto-generated by ralph.py
# This file will be deleted after the loop completes

param(
    [ValidateSet("plan", "build")]
    [string]$Mode = "plan",
    [int]$MaxIterations = 2,
    [string]$Model = "opus"
)

# Absolute paths baked in by ralph.py - no relative resolution needed
$FeatureDir = "C:\Users\Grove\OneDrive\Documents\PYTHON\claude_plugins\vista-expanded-visualization\.vista\ralph\share-docs-v2-plan-e4e41dc2-a1c7-433c-8fae-794905daace6"
$ProjectRoot = "C:\Users\Grove\OneDrive\Documents\PYTHON\claude_plugins\vista-expanded-visualization"

# Prevent child MCP servers from opening the browser
$env:RALPH_SERVER_AUTO_OPEN = "false"

# Set prompt file based on mode
$PromptFile = Join-Path $FeatureDir "PROMPT_$Mode.md"
$ProgressFile = Join-Path $FeatureDir "progress.txt"
$TaskFile = Join-Path $FeatureDir "task.md"

# Get current branch (cwd is already $ProjectRoot)
$CurrentBranch = git branch --show-current

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Feature:  share-docs-v2-plan"
Write-Host "Provider: Claude Code"
Write-Host "Mode:     $Mode"
Write-Host "Model:    $Model"
Write-Host "Branch:  $CurrentBranch"
Write-Host "Prompt:  $PromptFile"
if ($MaxIterations -gt 0) {
    Write-Host "Max:     $MaxIterations iterations"
} else {
    Write-Host "Max:     unlimited"
}
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan

# Verify prompt file exists
if (-not (Test-Path $PromptFile)) {
    Write-Host "Error: $PromptFile not found" -ForegroundColor Red
    exit 1
}

$Iteration = 0

while ($true) {
    if ($MaxIterations -gt 0 -and $Iteration -ge $MaxIterations) {
        Write-Host "`nReached max iterations: $MaxIterations" -ForegroundColor Yellow
        break
    }

    $Iteration++
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

    Write-Host ""
    Write-Host "======================== ITERATION $Iteration ========================" -ForegroundColor Green
    Write-Host "Started: $Timestamp"
    Write-Host ""

    # Compose prompt with optional task/progress context
    $PromptContent = Get-Content $PromptFile -Raw
    $TaskContent = Get-Content $TaskFile -Raw -ErrorAction SilentlyContinue
    $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
    if ($TaskContent) {
        $PromptContent = "$PromptContent`n`n## Task`n$TaskContent"
    }
    if ($ProgressContent) {
        $PromptContent = "$PromptContent`n`n## Current Progress`n$ProgressContent"
    }
    $PromptContent | claude -p `
        --dangerously-skip-permissions `
        --output-format=stream-json `
        --model $Model `
        --verbose
    $AgentExitCode = $LASTEXITCODE
    if ($AgentExitCode -ne 0) {
        Write-Host "Agent invocation failed with exit code $AgentExitCode" -ForegroundColor Red
        exit $AgentExitCode
    }

    # Push changes after each iteration
    git push origin $CurrentBranch
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to push. Creating remote branch..." -ForegroundColor Yellow
        git push -u origin $CurrentBranch
    }

    Write-Host ""
    Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm')] ITERATION $Iteration complete" -ForegroundColor Green

    # Check if all phases complete (build mode only)
    if ($Mode -eq "build") {
        $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
        if ($ProgressContent -match "ALL PHASES COMPLETE") {
            Write-Host "`nAll phases complete! Stopping loop." -ForegroundColor Green
            break
        }
    }
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Loop finished after $Iteration iteration(s)"
Write-Host "Check: $ProgressFile"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
