#!/usr/bin/env python3
"""
Ralph Loop Runner - Configuration & Control Layer

1. Ask user: feature, mode, iterations, model
2. Copy prompt template and loop script into feature directory
3. Run the loop script from feature directory
4. Clean up copied files when done
"""

import os
import sys
import subprocess
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
FEATURES_DIR = PROJECT_ROOT / ".vista" / "features"
TEMPLATES_DIR = SCRIPT_DIR / "templates"

# Allow importing from server.services when running standalone
sys.path.insert(0, str(PROJECT_ROOT))
from server.services.provider_service import (
    Provider,
    get_enabled_providers,
    get_provider_by_name,
)

# Template loop script content - matches working loop.ps1
LOOP_SCRIPT_TEMPLATE = '''# Feature Loop - Auto-generated by ralph.py
# This file will be deleted after the loop completes

param(
    [ValidateSet("plan", "build")]
    [string]$Mode = "{mode}",
    [int]$MaxIterations = {max_iterations},
    [string]$Model = "{model}"
)

# Absolute paths baked in by ralph.py - no relative resolution needed
$FeatureDir = "{feature_dir_abs}"
$ProjectRoot = "{project_root_abs}"

# Prevent child MCP servers from opening the browser
$env:RALPH_SERVER_AUTO_OPEN = "false"

# Set prompt file based on mode
$PromptFile = Join-Path $FeatureDir "PROMPT_$Mode.md"
$ProgressFile = Join-Path $FeatureDir "progress.txt"
$TaskFile = Join-Path $FeatureDir "task.md"

# Get current branch (cwd is already $ProjectRoot)
$CurrentBranch = git branch --show-current

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Feature:  {feature_name}"
Write-Host "Provider: {provider_name}"
Write-Host "Mode:     $Mode"
Write-Host "Model:    $Model"
Write-Host "Branch:  $CurrentBranch"
Write-Host "Prompt:  $PromptFile"
if ($MaxIterations -gt 0) {{
    Write-Host "Max:     $MaxIterations iterations"
}} else {{
    Write-Host "Max:     unlimited"
}}
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan

# Verify prompt file exists
if (-not (Test-Path $PromptFile)) {{
    Write-Host "Error: $PromptFile not found" -ForegroundColor Red
    exit 1
}}

$Iteration = 0

while ($true) {{
    if ($MaxIterations -gt 0 -and $Iteration -ge $MaxIterations) {{
        Write-Host "`nReached max iterations: $MaxIterations" -ForegroundColor Yellow
        break
    }}

    $Iteration++
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

    Write-Host ""
    Write-Host "======================== ITERATION $Iteration ========================" -ForegroundColor Green
    Write-Host "Started: $Timestamp"
    Write-Host ""

    # Compose prompt with optional task/progress context
    $PromptContent = Get-Content $PromptFile -Raw
    $TaskContent = Get-Content $TaskFile -Raw -ErrorAction SilentlyContinue
    $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
    if ($TaskContent) {{
        $PromptContent = "$PromptContent`n`n## Task`n$TaskContent"
    }}
    if ($ProgressContent) {{
        $PromptContent = "$PromptContent`n`n## Current Progress`n$ProgressContent"
    }}
    {invocation_block}
    $AgentExitCode = $LASTEXITCODE
    if ($AgentExitCode -ne 0) {{
        Write-Host "Agent invocation failed with exit code $AgentExitCode" -ForegroundColor Red
        exit $AgentExitCode
    }}

    # Push changes after each iteration
    git push origin $CurrentBranch
    if ($LASTEXITCODE -ne 0) {{
        Write-Host "Failed to push. Creating remote branch..." -ForegroundColor Yellow
        git push -u origin $CurrentBranch
    }}

    Write-Host ""
    Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm')] ITERATION $Iteration complete" -ForegroundColor Green

    # Check if all phases complete (build mode only)
    if ($Mode -eq "build") {{
        $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
        if ($ProgressContent -match "ALL PHASES COMPLETE") {{
            Write-Host "`nAll phases complete! Stopping loop." -ForegroundColor Green
            break
        }}
    }}
}}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Loop finished after $Iteration iteration(s)"
Write-Host "Check: $ProgressFile"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
'''



# Provider classes imported from server.services.provider_service above


# ---------------------------------------------------------------------------


def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')


def print_header():
    print()
    print("=" * 56)
    print("        RALPH LOOP RUNNER")
    print("=" * 56)
    print()


def get_features():
    """Get list of feature directories."""
    if not FEATURES_DIR.exists():
        return []
    return sorted([d.name for d in FEATURES_DIR.iterdir() if d.is_dir()])


def select_from_menu(title, options):
    """Display menu and get user selection."""
    print(f"\n{title}")
    print("-" * 40)
    for i, opt in enumerate(options, 1):
        print(f"  {i}) {opt}")
    print()

    while True:
        try:
            choice = input(f"Select [1-{len(options)}]: ").strip()
            num = int(choice)
            if 1 <= num <= len(options):
                return options[num - 1], num - 1
        except (ValueError, KeyboardInterrupt):
            pass
        print("Invalid choice, try again.")


def get_prompt_content(mode: str, feature_name: str, feature_dir: Path) -> str:
    """Get prompt content from template with variable substitution."""
    filename = f"PROMPT_{mode}.md"
    template_path = TEMPLATES_DIR / filename

    if not template_path.exists():
        return None

    content = template_path.read_text(encoding='utf-8')

    # Variable substitution
    content = content.replace("{{FEATURE_NAME}}", feature_name)
    content = content.replace("{{FEATURE_DIR}}", str(feature_dir).replace("\\", "/"))
    content = content.replace("{{PROJECT_NAME}}", PROJECT_ROOT.name)

    return content


def run_loop(feature: str, mode: str, model: str, max_iterations: int,
             provider: Provider):
    """Copy files, run loop, clean up."""
    feature_dir = FEATURES_DIR / feature

    # Files we'll create
    prompt_file = feature_dir / f"PROMPT_{mode}.md"
    loop_script = feature_dir / "loop.ps1"

    # Track what we created for cleanup
    created_files = []

    try:
        # Step 1: Copy/create prompt file if it doesn't exist
        if not prompt_file.exists():
            prompt_content = get_prompt_content(mode, feature, feature_dir)
            if not prompt_content:
                print(f"\nError: Template not found: {TEMPLATES_DIR / f'PROMPT_{mode}.md'}")
                return
            prompt_file.write_text(prompt_content, encoding='utf-8')
            created_files.append(prompt_file)
            print(f"  Created: {prompt_file.name}")
        else:
            print(f"  Using existing: {prompt_file.name}")

        # Step 2: Always regenerate loop script (provider/model may have changed)
        script_content = LOOP_SCRIPT_TEMPLATE.format(
            mode=mode,
            max_iterations=max_iterations,
            model=model,
            feature_name=feature,
            feature_dir_abs=str(feature_dir.resolve()),
            project_root_abs=str(PROJECT_ROOT.resolve()),
            provider_name=provider.display_name,
            invocation_block=provider.get_invocation("ps1"),
        )
        loop_script.write_text(script_content, encoding='utf-8')
        created_files.append(loop_script)
        print(f"  Created: {loop_script.name}")

        # Step 3: Run the loop script
        print()
        print("=" * 56)
        print("  Starting loop...")
        print("=" * 56)
        print()

        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(loop_script)],
            cwd=str(PROJECT_ROOT.resolve()),  # Agent must start at project root
        )

    except KeyboardInterrupt:
        print("\n\nInterrupted by user.")
    except Exception as e:
        print(f"\nError: {e}")
    finally:
        # Step 4: Clean up files we created
        if created_files:
            print()
            print("-" * 40)
            print("Cleaning up temporary files...")
            for f in created_files:
                try:
                    if f.exists():
                        f.unlink()
                        print(f"  Deleted: {f.name}")
                except Exception as e:
                    print(f"  Failed to delete {f.name}: {e}")


def main():
    clear_screen()
    print_header()

    # Load provider settings (uses server.services.provider_service)
    providers = get_enabled_providers()
    if not providers:
        print("No providers enabled. Check settings.json")
        sys.exit(1)

    step = 1

    # Step 1: Select feature
    features = get_features()
    if not features:
        print(f"No features found in: {FEATURES_DIR}")
        sys.exit(1)

    feature, _ = select_from_menu(f"Step {step}: Select Feature", features)
    print(f"  -> {feature}")
    step += 1

    # Step 2: Select provider (skip if only one)
    if len(providers) == 1:
        provider = providers[0]
        print(f"\n  Provider: {provider.display_name} (only enabled provider)")
    else:
        provider_labels = [p.display_name for p in providers]
        label, idx = select_from_menu(f"Step {step}: Select Provider", provider_labels)
        provider = providers[idx]
        print(f"  -> {provider.display_name}")
        step += 1

    # Step N: Select mode
    modes = ["plan", "build"]
    mode, _ = select_from_menu(f"Step {step}: Select Mode", modes)
    print(f"  -> {mode}")
    step += 1

    # Step N+1: Select model (dynamic per provider)
    print(f"\n  Retrieving models for {provider.display_name}...")
    models = provider.get_models()
    model, _ = select_from_menu(f"Step {step}: Select Model", models)
    print(f"  -> {model}")
    step += 1

    # Step N+2: Select iterations
    iter_options = ["Single (1)", "Limited (3)", "Limited (5)", "Limited (10)", "Unlimited"]
    iter_choice, idx = select_from_menu(f"Step {step}: Max Iterations", iter_options)
    max_iter = [1, 3, 5, 10, 0][idx]
    print(f"  -> {iter_choice}")

    # Confirm
    feature_dir = FEATURES_DIR / feature
    print()
    print("=" * 56)
    print(f"  Feature:     {feature}")
    print(f"  Provider:    {provider.display_name}")
    print(f"  Mode:        {mode}")
    print(f"  Model:       {model}")
    print(f"  Iterations:  {'unlimited' if max_iter == 0 else max_iter}")
    print(f"  Directory:   {feature_dir}")
    print("=" * 56)
    print()

    confirm = input("Start loop? [Y/n]: ").strip().lower()
    if confirm and confirm != 'y':
        print("Cancelled.")
        return

    # Run the loop
    run_loop(feature, mode, model, max_iter, provider)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nExited.")
        sys.exit(0)
