"""Bash loop script generator for containerized execution.

Pure string generation — no filesystem or Docker dependencies.
"""

from __future__ import annotations

# Use double braces {{ }} for literal bash braces in the template,
# single braces for Python format() substitution.
BASH_LOOP_TEMPLATE = r'''#!/bin/bash
set -e

# Feature Loop - Auto-generated by Vista BashLoopGenerator
# This script runs inside a Docker container at /workspace

MODE="{mode}"
MAX_ITERATIONS={max_iterations}
MODEL="{model}"
FEATURE_DIR="{feature_dir_abs}"
PROJECT_ROOT="{project_root_abs}"
JOB_DIR="{job_dir_abs}"
PROMPT_FILE="$JOB_DIR/PROMPT_$MODE.md"
PROGRESS_FILE="$JOB_DIR/progress.txt"
TASK_FILE="$JOB_DIR/task.md"
OUTPUT_LOG="$JOB_DIR/output.log"

# Get current branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")

echo "========================================================"
echo "Feature:  {feature_name}"
echo "Provider: {provider_name}"
echo "Mode:     $MODE"
echo "Model:    $MODEL"
echo "Branch:   $CURRENT_BRANCH"
echo "Prompt:   $PROMPT_FILE"
if [ $MAX_ITERATIONS -gt 0 ]; then
    echo "Max:      $MAX_ITERATIONS iterations"
else
    echo "Max:      unlimited"
fi
echo "========================================================"

# Verify prompt file exists
if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: $PROMPT_FILE not found"
    exit 1
fi

ITERATION=0

while true; do
    if [ $MAX_ITERATIONS -gt 0 ] && [ $ITERATION -ge $MAX_ITERATIONS ]; then
        echo ""
        echo "Reached max iterations: $MAX_ITERATIONS"
        break
    fi

    ITERATION=$((ITERATION + 1))
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M")

    echo ""
    echo "======================== ITERATION $ITERATION ========================"
    echo "Started: $TIMESTAMP"
    echo ""

    # Compose prompt with optional task/progress context
    PROMPT_CONTENT=$(cat "$PROMPT_FILE")
    if [ -f "$TASK_FILE" ]; then
        TASK_CONTENT=$(cat "$TASK_FILE")
        PROMPT_CONTENT="$PROMPT_CONTENT

## Task
$TASK_CONTENT"
    fi
    if [ -f "$PROGRESS_FILE" ]; then
        PROGRESS_CONTENT=$(cat "$PROGRESS_FILE")
        PROMPT_CONTENT="$PROMPT_CONTENT

## Current Progress
$PROGRESS_CONTENT"
    fi

    # Provider invocation
    {invocation_block}

    AGENT_EXIT_CODE=$?
    if [ $AGENT_EXIT_CODE -ne 0 ]; then
        echo "Agent invocation failed with exit code $AGENT_EXIT_CODE"
        exit $AGENT_EXIT_CODE
    fi

    # Push changes after each iteration
    git push origin "$CURRENT_BRANCH" 2>/dev/null || {{
        echo "Failed to push. Creating remote branch..."
        git push -u origin "$CURRENT_BRANCH" 2>/dev/null || true
    }}

    echo ""
    echo "[$(date +"%Y-%m-%d %H:%M")] ITERATION $ITERATION complete"

    # Check if all phases complete (build mode only)
    if [ "$MODE" = "build" ]; then
        if [ -f "$PROGRESS_FILE" ] && grep -q "ALL PHASES COMPLETE" "$PROGRESS_FILE"; then
            echo ""
            echo "All phases complete! Stopping loop."
            break
        fi
    fi
done

echo ""
echo "========================================================"
echo "Loop finished after $ITERATION iteration(s)"
echo "Check: $PROGRESS_FILE"
echo "========================================================"
'''

# Provider-specific invocation blocks
_CLAUDE_INVOCATION = r'''    printf '%s' "$PROMPT_CONTENT" | claude -p \
        --dangerously-skip-permissions \
        --output-format=stream-json \
        --model "$MODEL" \
        --verbose 2>&1 | tee -a "$OUTPUT_LOG"'''

_OPENCODE_INVOCATION = r'''    opencode run \
        --model "$MODEL" \
        "$PROMPT_CONTENT" 2>&1 | tee -a "$OUTPUT_LOG"'''

_PROVIDER_INVOCATIONS = {
    "claude": _CLAUDE_INVOCATION,
    "opencode": _OPENCODE_INVOCATION,
}


class BashLoopGenerator:
    """Generate bash loop scripts for containerized execution."""

    @staticmethod
    def generate(
        mode: str,
        max_iterations: int,
        model: str,
        feature_name: str,
        feature_dir: str,
        project_root: str,
        job_dir: str,
        provider: str,
    ) -> str:
        """Generate a complete bash loop script.

        Args:
            mode: "plan" or "build"
            max_iterations: 0 for unlimited, >0 for capped
            model: Model name (e.g. "sonnet", "opus")
            feature_name: Human-readable feature name
            feature_dir: Relative path to feature dir (e.g. ".vista/features/foo")
            project_root: Container project root (always "/workspace")
            job_dir: Relative path to job dir (e.g. ".vista/ralph/foo-abc12345")
            provider: "claude" or "opencode"

        Returns:
            Complete bash script as string.
        """
        if mode not in ("plan", "build"):
            raise ValueError(f"Invalid mode: {mode}. Must be plan or build.")

        if max_iterations < 0:
            raise ValueError(f"max_iterations must be >= 0, got {max_iterations}")

        if provider not in _PROVIDER_INVOCATIONS:
            raise ValueError(
                f"Unknown provider: {provider}. Supported: {', '.join(_PROVIDER_INVOCATIONS)}"
            )

        invocation_block = _PROVIDER_INVOCATIONS[provider]

        # Map provider name to display name
        provider_display = {"claude": "Claude Code", "opencode": "OpenCode"}.get(
            provider, provider
        )

        # Build absolute paths from project_root + relative paths
        feature_dir_abs = f"{project_root}/{feature_dir}"
        job_dir_abs = f"{project_root}/{job_dir}"

        script = BASH_LOOP_TEMPLATE.format(
            mode=mode,
            max_iterations=max_iterations,
            model=model,
            feature_name=feature_name,
            feature_dir_abs=feature_dir_abs,
            project_root_abs=project_root,
            job_dir_abs=job_dir_abs,
            provider_name=provider_display,
            invocation_block=invocation_block,
        )

        return script
