# Feature Loop - Auto-generated by ralph.py
# This file will be deleted after the loop completes

param(
    [ValidateSet("plan", "build")]
    [string]$Mode = "plan",
    [int]$MaxIterations = 1,
    [string]$Model = "sonnet"
)

# Absolute paths baked in by ralph.py - no relative resolution needed
$FeatureDir = "C:\Users\Grove\OneDrive\Documents\PYTHON\claude_plugins\vista\.vista\ralph\activity-log-test"
$ProjectRoot = "C:\Users\Grove\OneDrive\Documents\PYTHON\claude_plugins\vista"

# Set prompt file based on mode
$PromptFile = Join-Path $FeatureDir "PROMPT_$Mode.md"
$ProgressFile = Join-Path $FeatureDir "progress.txt"

# Get current branch (cwd is already $ProjectRoot)
$CurrentBranch = git branch --show-current

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Feature:  activity-log-test"
Write-Host "Provider: Claude Code"
Write-Host "Mode:     $Mode"
Write-Host "Model:    $Model"
Write-Host "Branch:  $CurrentBranch"
Write-Host "Prompt:  $PromptFile"
if ($MaxIterations -gt 0) {
    Write-Host "Max:     $MaxIterations iterations"
} else {
    Write-Host "Max:     unlimited"
}
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan

# Verify prompt file exists
if (-not (Test-Path $PromptFile)) {
    Write-Host "Error: $PromptFile not found" -ForegroundColor Red
    exit 1
}

$Iteration = 0

while ($true) {
    if ($MaxIterations -gt 0 -and $Iteration -ge $MaxIterations) {
        Write-Host "`nReached max iterations: $MaxIterations" -ForegroundColor Yellow
        break
    }

    $Iteration++
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

    Write-Host ""
    Write-Host "======================== ITERATION $Iteration ========================" -ForegroundColor Green
    Write-Host "Started: $Timestamp"
    Write-Host ""

    # Run agent with the prompt
    $PromptContent = Get-Content $PromptFile -Raw
    $PromptContent | claude -p `
        --dangerously-skip-permissions `
        --output-format=stream-json `
        --model $Model `
        --verbose

    # Push changes after each iteration
    git push origin $CurrentBranch
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to push. Creating remote branch..." -ForegroundColor Yellow
        git push -u origin $CurrentBranch
    }

    Write-Host ""
    Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm')] ITERATION $Iteration complete" -ForegroundColor Green

    # Check if all phases complete (build mode only)
    if ($Mode -eq "build") {
        $ProgressContent = Get-Content $ProgressFile -Raw -ErrorAction SilentlyContinue
        if ($ProgressContent -match "ALL PHASES COMPLETE") {
            Write-Host "`nAll phases complete! Stopping loop." -ForegroundColor Green
            break
        }
    }
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Loop finished after $Iteration iteration(s)"
Write-Host "Check: $ProgressFile"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
